mysql:
  dsn:  root:password@tcp(127.0.0.1:3306)/ecomm?charset=utf8mb4&parseTime=True&loc=Local
kafka:
  server:
    - localhost:9092
token:
  key : this_is_my_token_key
  rkey: this_is_my_refresh_token_key
redis:
  addr: 127.0.0.1:6379
  db: 1
  pass: ""
server:
  host: localhost